export const HEALTH_INSURANCE_INCOME_THRESHOLD = 66150;
export const HEALTH_INSURANCE_GENERAL_RATE = 14.6;
export const PENSION_INSURANCE_INCOME_THRESHOLD = 96600;
export const PENSION_INSURANCE_CONTRIBUTION_RATE = 18.6;
export const UNEMPLOYMENT_INSURANCE_INCOME_THRESHOLD =
  PENSION_INSURANCE_INCOME_THRESHOLD;
export const UNEMPLOYMENT_INSURANCE_CONTRIBUTION_RATE = 2.6;
