export const HEALTH_INSURANCE_SALARY_THRESHOLD_YEAR = 66150;
export const HEALTH_INSURANCE_SALARY_THRESHOLD_MONTH = 5512.5;
export const HEALTH_INSURANCE_GENERAL_RATE = 14.6;

export const PENSION_INSURANCE_SALARY_THRESHOLD_YEAR = 96600;
export const PENSION_INSURANCE_SALARY_THRESHOLD_MONTH = 8050;
export const PENSION_INSURANCE_CONTRIBUTION_RATE = 18.6;

export const UNEMPLOYMENT_INSURANCE_SALARY_THRESHOLD_YEAR = PENSION_INSURANCE_SALARY_THRESHOLD_YEAR;
export const UNEMPLOYMENT_INSURANCE_SALARY_THRESHOLD_MONTH =
  PENSION_INSURANCE_SALARY_THRESHOLD_MONTH;
export const UNEMPLOYMENT_INSURANCE_CONTRIBUTION_RATE = 2.6;
