export enum GermanFederalState {
  BadenWuerttemberg = "BW",
  Bavaria = "BY",
  Berlin = "BE",
  Brandenburg = "BB",
  Bremen = "HB",
  Hamburg = "HH",
  Hesse = "HE",
  LowerSaxony = "NI",
  MecklenburgWesternPomerania = "MV",
  NorthRhineWestphalia = "NW",
  RhinelandPalatinate = "RP",
  Saarland = "SL",
  Saxony = "SN",
  SaxonyAnhalt = "ST",
  SchleswigHolstein = "SH",
  Thuringia = "TH",
}
