import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { getLocale, getMessages } from 'next-intl/server';

import './globals.css';
import Provider from './provider';

export const metadata: Metadata = {
  title: 'Brutto Netto',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className="antialiased dark">
        <Provider
          locale={locale}
          messages={messages}
        >
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
